### ISSUE TITLE
遇到两个不同的问题

### ISSUE THREAD

**Issue by misaka4694** [JamXi233/SRTools#10]
问题1
2023/12/11 12:10:59 [1] 
应用程序:System.Private.CoreLib
错误标题:Length cannot be less than zero. (Parameter 'length')
堆栈跟踪:
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at SRTools.Views.GachaView.GetCacheGacha()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
结束代码:-2146233086
<img width="758" alt="屏幕截图 2023-12-11 121025" src="https://github.com/JamXi233/SRTools/assets/153478293/2da240f0-38e4-435e-b7e6-dd05e32705b6">

问题2
2023/12/11 12:04:01 [1] 
应用程序:System.Net.Http
错误标题:An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
堆栈跟踪:
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.GetStreamAsync(Uri requestUri, CancellationToken cancellationToken)
   at SRTools.Views.MainView.LoadAdvertisementData()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
结束代码:-2146233079
![Uploading 屏幕截图 2023-12-11 121340.png…]()

**Comment by JamXi233** [comment]
上方的问题可以尝试在设置中清除数据看能否解决问题(如果本身没有抽卡记录的情况下)
下方的问题今晚会修复

**Comment by misaka4694** [comment]
我使用了设置中的清空所有数据，然后重启完按照步骤重新安装了依赖，但是抽卡检测页面还是显示：Length cannot be less than zero

**Comment by JamXi233** [comment]
已经解决 2896f9b79b1556b5a27b835e18b27c0e3833c169
