### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Gerald2042** [JamXi233/SRTools#16]
3/9/2024 9:09:01 PM [1] 
应用程序:System.Private.CoreLib
错误标题:Length cannot be less than zero. (Parameter 'length')
堆栈跟踪:
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at SRTools.Views.GachaView.GetCacheGacha()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
结束代码:-2146233086

**Comment by JamXi233** [comment]
#10

**Comment by JamXi233** [comment]
已经解决 2896f9b79b1556b5a27b835e18b27c0e3833c169
