### ISSUE TITLE
严重错误：Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by WILLINGG** [JamXi233/SRTools#33]
<img width="751" alt="屏幕截图 2024-06-19 225034" src="https://github.com/JamXi233/SRTools/assets/148088065/8bef7d34-8df3-4221-979a-b1bc32ea8adf">

2024/6/19 22:45:35 [1] 
应用程序:SRTools
错误标题:Object reference not set to an instance of an object.
堆栈跟踪:
   at SRTools.MainWindow.BackgroundImage()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
结束代码:-2147467261

**Comment by JamXi233** [comment]
已在[SRTools_1.3.1.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.1.0)中修复
**⚠️注意:SRTools_1.3.0.1的软件内更新存在问题⚠️
⚠️需到Powershell进行更新⚠️
➡️`irm wavetools.jamsg.cn/get | iex`**
