### ISSUE TITLE
严重错误

### ISSUE THREAD

**Issue by Lorentz114514** [JamXi233/SRTools#36]
这一阵打开之后是这样的
<img width="325" alt="PixPin_2024-06-24_12-12-31" src="https://github.com/JamXi233/SRTools/assets/173653308/89785baa-8b53-49b0-a4a0-bf44a8773f49">
这是错误报告

**Comment by Lorentz114514** [comment]
2024/6/24 12:12:55 [1] 
源:SRTools
错误标题:Object reference not set to an instance of an object.
堆栈跟踪:
   at SRTools.Views.MainView.LoadPicturesAsync()
   at SRTools.Views.MainView.MainView_Loaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
内部异常:

结束代码:-2147467261

**Comment by Lorentz114514** [comment]
不影响启动，但是一直有这个提示

**Comment by JamXi233** [comment]
#25 请参考后重新编辑Issue

**Comment by JamXi233** [comment]
已经超过两周没有收到您的回复，将关闭该issue。
