### ISSUE TITLE
首页加载报错

### ISSUE THREAD

**Issue by Ireeul** [JamXi233/SRTools#8]
![屏幕截图 2023-12-06 153901](https://github.com/JamXi233/SRTools/assets/150488267/324a2aa0-b9ff-417a-ad2d-e986ca1448e3)

2023/12/6 15:38:49 [1] 
应用程序:System.Net.Http
错误标题:An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
堆栈跟踪:
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.GetStreamAsync(Uri requestUri, CancellationToken cancellationToken)
   at SRTools.Views.MainView.LoadAdvertisementData()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at SRTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
结束代码:-2146233079

**Comment by JamXi233** [comment]
下个版本将会解决该问题

**Comment by Ireeul** [comment]
辛苦大佬！顺便问下有做服务器切换功能的打算吗？非常冒昧很抱歉，谢谢大佬能持续运营工具箱！

**Comment by JamXi233** [comment]
有时间的话会做的

**Comment by misaka4694** [comment]
我遇到了相同的问题，请问在下个版本更新之前有什么能做的来解决这个问题吗

**Comment by JamXi233** [comment]
> 我遇到了相同的问题，请问在下个版本更新之前有什么能做的来解决这个问题吗

由于官方API修改，所以暂时没有可以在启动器端解决的方案，但是如果不出问题的话今晚就会更新

**Comment by JamXi233** [comment]
[SRTools_1.2.3.0](https://github.com/JamXi233/SRTools/releases/tag/1.2.3.0)
✴️修复主菜单严重错误问题
